-- Exercício 1
CREATE TABLE CLIENTE (
  ID INT PRIMARY KEY,
  NOME VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL UNIQUE,
  CPF CHAR(11) NOT NULL UNIQUE,
  Data_de_entrada DATE
);

CREATE TABLE PEDIDO (
  ID INT PRIMARY KEY,
  DATA TIMESTAMP,
  Total_da_compra DECIMAL(10,2),
  Situação_do_pedido VARCHAR(8),
  ID_CLIENTE INT,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);

CREATE TABLE item_pedido (
  ID INT PRIMARY KEY,
  Nome VARCHAR(255) NOT NULL,
  Preço DECIMAL(8,2) not NULL,
  Quantidade INT not NULL,
  ID_PEDIDO INT,
  FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID)
);

INSERT INTO CLIENTE VALUES(0001, 'Bruce Cage', 'cage.bruce@gmail.com', '45901203909', '2002-02-09');
INSERT INTO CLIENTE VALUES(0021, 'Mike Walk', 'mike.walk@gmail.com', '65908490798', '2020-05-29');
